# WARNING: NEVER EDIT config.yml
# Instead, copy any sections you want to change to local.yml and edit them there.
#

# Your secret key for verifying cookie session data integrity.
# If you change this key, all old sessions will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.

# do not use the defaults in production!
SESSION_KEY: '_otwarchive_session'
SESSION_SECRET: '898f6d0363863ec79d782238cd1c5767636d712cc0d138238bcd5bfc9d2672fb852380050e52c03a0401175d909c09dba48512a119d46b126a84c2dd05716eb5'

RETURN_ADDRESS: 'do-not-reply@example.org'
SUPPORT_ADDRESS: 'support@example.org'
ABUSE_ADDRESS: 'abuse@example.org'
QUESTION_ADDRESS: 'questions@example.org'
WEBMASTER_ADDRESS: 'webmaster@example.org'
ERROR_ADDRESS: errors@example.org
FEEDBACK_ADDRESS: feedback@example.org
ERROR_PREFIX: "[ERROR] "
# Because the default email addresses are fake,
# email delivery is turned off by default, even for production.
# The log file will nonetheless show "Sent mail:"
PERFORM_DELIVERIES: false

APP_URL: 'http://www.example.org'
APP_NAME: 'Example Archive'
LOGO: 'OTWLogo.png'
ALT_LOGO: 'OTW Logo:closing the circle of the copyright symbol, it symbolizes our creative engagement with media: participating and not just consuming.'
REVISION: ''

# tag settings
DELIMITER: ', '  # if you change this, you probably need to change the label regexp as well

SMTP_SERVER: localhost
SMTP_PORT: 25
SMTP_DOMAIN: localhost
# if required for email authentication
#SMTP_USER: 
#SMTP_PASSWORD: 
#SMTP_AUTHENTICATION: # :plain, :login or :cram_md5

ACCOUNT_CREATION_ENABLED: true
TITLE_MAX: 255
TITLE_MIN: 3
SUMMARY_MAX: 1250
NOTES_MAX: 2500
COMMENT_MAX: 4300
TAG_MAX: 42
CONTENT_MIN: 10
CONTENT_MAX: 500000
COMMENT_THREAD_MAX_DEPTH: 2
NUMBER_OF_ITEMS_VISIBLE_IN_DASHBOARD: 5

# This is used to determine how many recent items
# to cache for recent lookups -- eg if we want to 
# provide a "ten most recent" items to browse.
# used in CacheFinds module -- include CacheFinds in a model
# and the methods Model.recent and Model.last(#) will be
# enabled, cached on production/test environments.
MAX_RECENT: 20

# Only the following fields are allowed to have HTML. In all others, 
# all HTML tags will be stripped.
FIELDS_ALLOWING_HTML: %w(content summary notes about_me comment)

# variables for Askimet http://akismet.com/
AKISMET_KEY: '6833ee7298cf'
AKISMET_NAME: 'http://transformativeworks.org'

DEFAULT_LOCALE: 'en'
BASE_LANGUAGE: 'en-US'    # must be one of the following
SUPPORTED_LOCALES: { en: en-US,
 it: it-IT,
 fr: fr-FR,
 de: de-DE,
 ja: ja-JP,
 es: es-ES,
 cs: cs-CZ,
 zh: zh-CHS,
 ru: ru-RU,
 pt: pt-BR,
 nl: nl-NL,
 id: id-ID,
 fi: fi-FI }

#Allow OpenID Authentication
USE_OPENID: true

# Allow orphaninig
ORPHANING_ALLOWED: true

# Help directory, must be in the public folder. 
# Create subfolders for each supported language 
# (eg, /help/fr/ contains the French versions of the help)
HELP_DIRECTORY: '/help'

# only use if you are running your app completely in a subfolder of your domain
#PRODUCTION_URL_ROOT: "/archive"

# turn delta indexes on and off
USE_DELTA_INDEXING: false
