# WARNING: NEVER EDIT config.yml
# Instead, copy any sections you want to change to local.yml and edit them there.
#

# Your secret key for verifying cookie session data integrity.
# If you change this key, all old sessions will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.

# do not use the defaults in production!
SESSION_KEY: '_otwarchive_session'
SESSION_SECRET: '898f6d0363863ec79d782238cd1c5767636d712cc0d138238bcd5bfc9d2672fb852380050e52c03a0401175d909c09dba48512a119d46b126a84c2dd05716eb5'

RETURN_ADDRESS: 'do-not-reply@example.org'
SUPPORT_ADDRESS: 'support@example.org'
ABUSE_ADDRESS: 'abuse@example.org'
QUESTION_ADDRESS: 'questions@example.org'
WEBMASTER_ADDRESS: 'webmaster@example.org'
ERROR_ADDRESS: errors@example.org
FEEDBACK_ADDRESS: feedback@example.org
ERROR_PREFIX: "[ERROR] "
# Because the default email addresses are fake,
# email delivery is turned off by default, even for production.
# The log file will nonetheless show "Sent mail:"
PERFORM_DELIVERIES: false

APP_URL: 'http://www.example.org'
APP_NAME: 'Example Archive'
LOGO: 'OTWLogo.png'
ALT_LOGO: 'OTW Logo:closing the circle of the copyright symbol, it symbolizes our creative engagement with media: participating and not just consuming.'
REVISION: ''

# tag settings
DELIMITER: ', '  # if you change this, you probably need to change the label regexp as well

SMTP_SERVER: localhost
SMTP_PORT: 25
SMTP_DOMAIN: localhost
# if required for email authentication
#SMTP_USER: 
#SMTP_PASSWORD: 
#SMTP_AUTHENTICATION: # :plain, :login or :cram_md5

ACCOUNT_CREATION_ENABLED: true
TITLE_MAX: 255
TITLE_MIN: 3
SUMMARY_MAX: 1250
NOTES_MAX: 2500
COMMENT_MAX: 4300
TAG_MAX: 42
CONTENT_MIN: 10
CONTENT_MAX: 500000
COMMENT_THREAD_MAX_DEPTH: 2
MAX_COMMENTS_TO_BROWSE: 30
NUMBER_OF_ITEMS_VISIBLE_IN_DASHBOARD: 5

# Tags allowed by default in user-entered HTML
# Expand this list AT YOUR PERIL *doom doom doom*
ALLOWED_TAGS: %w(a href, b, br, p, i, em, strong, strike, u, ins, q, del, cite, blockquote, pre, code, small, sup, sub img)

# variables for Askimet http://akismet.com/
AKISMET_KEY: '6833ee7298cf'
AKISMET_NAME: 'http://transformativeworks.org'

BASE_LANGUAGE: 'en-US'    # must be one of the following
SUPPORTED_LOCALES: { en: en-US,
 it: it-IT,
 fr: fr-FR,
 de: de-DE,
 ja: ja-JP,
 es: es-ES,
 cs: cs-CZ,
 zh: zh-CHS,
 ru: ru-RU,
 pt: pt-BR,
 nl: nl-NL,
 id: id-ID,
 fi: fi-FI }

TOS: This is where the Terms of Service will go when they're finished. This is FAKE FAKE FAKE! Placeholder only! In no way should any of the text inside this box be assumed to have anything to do with the real live Terms of Service as devised by the Archive of Our Own project. No promises are intended. No policies are implemented. This is just a little something the coder is writing so the text box will scroll and she can see how the scrolling looks. Is it too big? Too small? Too short? Too tall? How do the dimensions look? The real Terms of Service are forthcoming and should be pasted into this section of this document.

#Allow OpenID Authentication
USE_OPENID: true

# Allow orphaninig
ORPHANING_ALLOWED: true

# Help directory, must be in the public folder. 
# Create subfolders for each supported language 
# (eg, /help/fr/ contains the French versions of the help)
HELP_DIRECTORY: '/help'

# only use if you are running your app completely in a subfolder of your domain
#PRODUCTION_URL_ROOT: "/archive"
