# session setup
SESSION_KEY: '_test_otwarchive_session'
SESSION_SECRET: 'Eipo1iufaokiechoomameingeeguzu ohW1aevoteishumieforeiquoopeez'

RETURN_ADDRESS: 'do-not-reply@test.com'

SUPPORTED_LOCALES: { en: en-US, fr: fr-FR }
