# session setup
SESSION_KEY: '_test_otwarchive_session'
SESSION_SECRET: 'Eipo1iufaokiechoomameingeeguzu ohW1aevoteishumieforeiquoopeez'

RETURN_ADDRESS: 'do-not-reply@test.com'

SUPPORTED_LOCALES: { en: en-US, fr: fr-FR }

RETURN_ADDRESS: 'do-not-reply@test.com'
ABUSE_ADDRESS: 'abuse@test.com'
WEBMASTER_ADDRESS: 'webmaster@test.com'
APP_URL: 'http://www.test.com'
APP_NAME: 'Test Archive'
